_id: "417980557096386560"
name: block-ai
description: "111"
model: gpt-3.5-turbo
createdAt: 2024-01-17T10:21:54.379Z
updatedAt: 2024-03-01T03:21:47.666Z
createdBy: z1hfptpNCvPcJwEoCVpgK5iq8dkn7uCad7E
updatedBy: z1hfptpNCvPcJwEoCVpgK5iq8dkn7uCad7E
pinnedAt: null
icon: https://bbqaz5tpm7zmfgc6s7p4urdkr7era7fj564f3goiqyy.did.abtnet.io/image-bin/uploads/82ec0f0001655d734b529e2a9ce1e561.png
gitType: default
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: true
