_id: "392528905124184064"
name: Felix-test
description: Test
model: gpt-3.5-turbo
createdAt: 2023-12-20T04:09:43.818Z
updatedAt: 2023-12-21T03:52:59.018Z
createdBy: z1hfptpNCvPcJwEoCVpgK5iq8dkn7uCad7E
updatedBy: z1hfptpNCvPcJwEoCVpgK5iq8dkn7uCad7E
pinnedAt: null
icon: https://bbqaz5tpm7zmfgc6s7p4urdkr7era7fj564f3goiqyy.did.abtnet.io/image-bin/uploads/2c2e4ec3dcd579a662569430de26f56a.png
gitType: default
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: null
