_id: "392528905124184064"
name: Felix-test
description: Test
model: ""
createdAt: 2023-12-20T04:09:43.818Z
updatedAt: 2023-12-20T04:09:43.818Z
createdBy: z1hfptpNCvPcJwEoCVpgK5iq8dkn7uCad7E
updatedBy: z1hfptpNCvPcJwEoCVpgK5iq8dkn7uCad7E
icon: ""
gitType: simple
temperature: 1
topP: 1
