_id: "402660215889068032"
name: "123"
description: null
model: gpt-3.5-turbo
createdAt: 2024-01-17T03:07:56.534Z
updatedAt: 2024-01-17T03:08:44.589Z
createdBy: z1hfptpNCvPcJwEoCVpgK5iq8dkn7uCad7E
updatedBy: z1hfptpNCvPcJwEoCVpgK5iq8dkn7uCad7E
pinnedAt: null
icon: https://bbqaz5tpm7zmfgc6s7p4urdkr7era7fj564f3goiqyy.did.abtnet.io/image-bin/uploads/2c2e4ec3dcd579a662569430de26f56a.png
gitType: default
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: null
