_id: "392528905124184064"
name: Felix-test
description: Test
model: gpt-3.5-turbo
createdAt: 2023-12-20T04:09:43.818Z
updatedAt: 2023-12-21T00:51:53.008Z
createdBy: z1hfptpNCvPcJwEoCVpgK5iq8dkn7uCad7E
updatedBy: z1hfptpNCvPcJwEoCVpgK5iq8dkn7uCad7E
pinnedAt: null
icon: https://bbqaz5tpm7zmfgc6s7p4urdkr7era7fj564f3goiqyy.did.abtnet.io/image-bin/uploads/028bf787919e3e25bd5aca113c5471bb.png
gitType: simple
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: null
