_id: "402769426518114304"
name: asd123123
description: null
model: ""
createdAt: 2024-01-17T10:21:54.379Z
updatedAt: 2024-01-17T12:15:50.465Z
createdBy: z1hfptpNCvPcJwEoCVpgK5iq8dkn7uCad7E
updatedBy: z1hfptpNCvPcJwEoCVpgK5iq8dkn7uCad7E
pinnedAt: null
icon: https://bbqaz5tpm7zmfgc6s7p4urdkr7era7fj564f3goiqyy.did.abtnet.io/image-bin/uploads/82ec0f0001655d734b529e2a9ce1e561.png
gitType: simple
temperature: 1
topP: 1
presencePenalty: null
frequencyPenalty: null
maxTokens: null
gitAutoSync: null
